### PR TITLE
New way to install 42 which windows

### PR DESCRIPTION
**Pull request by Eloypripan**
I find/do a new way developed by me to install the 42 in windows in a most easy way, I wish you add my contribution in your 42 repository, thank
I have trie teh code many times and it work almost always
Tip1: if sometingo dont work before the compile, try to do a "sudo apt update"
Tip2: if sometingo dont work durin the execution, try to change diplay number in the command "DISPAY=:1 ./42"

Thanks

Eloy

### CODE REVIEW

**Comment by Eloypripan** [comment]
Please, include this in your 42 repo

**Comment by ericstoneking** [comment]
Hi Eloy,

Thanks for this.  I tried to follow your instructions on my home computer, and I'm having some newbie problems that maybe you can walk me through.

1)  Ximg.  I installed it okay, but launching it appears to just start up a background server process.  I tried using XLaunch, but couldn't stumble on a successful combination of options (in particular, launching xterm).  Any suggestions?

2) No display.  I can run bash successfully from PowerShell.  I can run 42 successfully from there, without graphics.  But with graphics enabled, freeglut can't find the display.  I tried DISPLAY=:1 and some variations, with no success.  Maybe this is why we need Ximg?  I did have the Ximg server running in the background during these attempts, FWIW.

3) The file system is, to be blunt, hostile.  The unbuntu file structure is tucked layers deep in a *hidden* folder under my Users/eric/ folder.  Are we stuck with that, or can we tell folks where to put it so that they can find it?  That file structure needs to be visible to other tools, like the code editors, text editors, and Matlab/Octave/whatever postprocessing tools people have.  Hiding it away is just bad.

Also, I had to chmod u+rwx everything in there.  Is this your experience?  

If you can help me over the Ximg stumbling block, I'll investigate moving the file structure.  I'm guessing that fixing those two may solve my other issues.

Thanks,
-Eric

**Comment by ericstoneking** [comment]
Hi Eloy,

Okay, I've worked out my problems adequately.  I can get Xming going, and I launch xterm from the bash command line.  I can run 42 with graphics.  I also move my HOME folder to /mnt/c/Users/Eric, where all my other tools can see.  I've updated your instructions accordingly.  I should perform the whole process on a fresh Windows machine to make sure that I didn't leave out any steps.  It'll be a couple of weeks before I can get around to that.  The instructions will be in the next drop.

Thanks again for getting this going.  This should prove to be an easier solution than mingw.

Regards,
-Eric

**Comment by Eloypripan** [comment]
Hi Eric, 

Sorry for not having answered before; the emails with your comments arrived to me the saturday and I have been doing some tests trying to find the problems.
I'm very glad that you have tested that and I see that you had some problems and I leave you some comments of my experience.

I think all the problems come from the number 3 that you said. By default, (in my computer) the Ubuntu files are in /mnt/c/Windows/System32/ and I have the 42 folder there.
I think that all have to be in the default folder for work.
PowerShell(admin mode) for default runs in C: Windows\System32\ directory (I use that directory by default)
PowerShell(not admin mode) for default runs in C:\Users\yourusername directory (And you uses that directory by default)
And Ubuntu file system take the C: Windows/System32/ directory as /mnt/c/Windows/System32/ ( when bash executes, i think by default all directories are replaced from /WindowsDirectroyRoute/ to /mnt/WindowsDirectroyRoute/ )
and I run all the commands in the default one.
I also noticed that in the last comment I omitted the letter "L", I wrote "DISPAY" instead of "DISPLAY", fix that please. 

I also just try to execute the 42 and xming doesn't open.
What I do to fix that is to type in Cortana "XLaunch"; it will show an application that was installed together with Xming.
If you click twice it will open a configuration options window, and in the first step there are four options above, you choose multiple windows because 42 needs 2 windows,
And in the display you can leave the 0 or put a number between 0 and 57000, (according of Xming documentation, then this number have to be use later).
Then, click next until finish and after (I go to 42 folder which PowerShell) and it works with DISPLAY=:number  ./42 (number is the number that you put inside de DISPLAY text box in the first step of XLaunch window.
In summary, you only need to execute XLaunch and click next until finish and the command DISPLAY=:0 ./42 will start to work.

I also noticed that in the last step of the configuration you can create a config file in the options of multiple windows and display number 1, but I don't know where the config has to be saved, I tried to find the way to force Xming use that configuration by default, 
in another way, Xming have to be configurated which XLaunch any time you restart/turn off the computer, if computer never turn off I think the configurations stay working well.
I tested that by retarting the computer

Please do some test of that; here there is a summary of the steps (I suppose the computer is turn off so there is no "actived" configuration set for Xming):
1) Turn on computer
2) If I want to use 42, I open power shell (admin mode)
3) bash
4) cd 42 
#or the directory of your 42, I recomend to have 42 folder in the default directory that you are when you active the bash, I din't check if works in others folders)
5) DISPLAY=:0 ./42
6) It should give error, so:
7) Type XLxaunch in Cornana and run it
8) click next until finish, dont change anything
9) DISPLAY=:0 ./42  
10) It should work now, you only have to run Xlaunch only after you restart/turn off computer, so if you close 42 windows you only have to do: DISPLAY=:0

If you find a way to save a config of xlaunch in order to avoid that at any time the computer is restarted, tell me and add it to the instalation proccess.
If not, these steps are very quick to do and you can also add these steps in an execution section.

For example:
How to execute:
If you have turn off the computer or its the first install do the next steps:
1) type Xlaunch in Cornana and run it
2) click next until finish, dont change anything
3) open powersell and type bash
4) cd 42 
5) DISPLAY=:0  ./42

If you only close the 42, and you don't tuen off/restart computer, you only need to do the steps 4) and 5) for do another execution

Also I'm testing some commands to create a shortlink to 42 folder in the desktop, in that way other people will find it easily
Code that I used: 
(this only works if you 42 is intalled using Powershell admin so the default directory is C:\Windows\system32\42
`
!CREATE SHORTCUT:
$strDesktopFolder = [System.Environment]:: GetFolderPath(" Desktop ")
$ObjShell = New-Object -com "Wscript.Shell"
$ObjShortcut = $objShell.CreateShortcut($strDesktopFolder + "\42_folder.lnk")
$objShortcut.TargetPath = "C:\Windows\system32\42"
$objShortcut.Save()
pause    !this line is optional, you can use it if you do a PowerShell script 
`
END CODE

And you can also move 42 to desktop, if display error appear only run XLaunch, click next until finish and try again DISPLAY=:0 ./42

Add some notes for other peoble telling the issue of the configuration of Xming, it's and issue that will happen and it's very quikly to solve when you do it more than two times, is only run Xlanch and click next, is the most easy way to solve that issue, do some test restarting computer and that issue may appears

Regards,
-Eloy

PD1:  I will be very glad if my name Eloy Prieto Panadero appears as contributor in the instructions in the next release. You can also link my name to my github (https://github.com/Eloypripan/). Please don't forget to mention me in the next release.
PD2: Here is my personal email: eloyprietopanadero@gmail.com
I will be so glad if you write to me from your personal email, so I could have it for future contributions or if I have any problems using the 42 because I want to use it in a university project

**Comment by ericstoneking** [comment]
Hi Eloy,

I had a colleague successfully follow this procedure with no guidance from me, so it's good to go.  I'm not actually merging your changes, since I've incorporated your procedure (with my own edits) manually.

Thanks,
-Eric

**Pull request closed without merging**
