### PR TITLE
Link AcApp with the C Math Library

### LINKED ISSUE #8: Make error when making target `AcApp`
GCC: 8.3
When making target AcApp: `make AcApp`, the make process errors out. Here is the make output, [link](https://gist.github.com/acxz/668c4b2eb7e789bf39acfa612a001278).

### PR DESCRIPTION
**Pull request by acxz**
Resolves #8

### CODE REVIEW

**Comment by PeteBlanchard** [comment]
Or add '$(LIBS)' (instead of '-lm' directly).

**Comment by acxz** [comment]
@ericstoneking Can you take a look at this PR?

**Comment by ericstoneking** [comment]
It'll be fixed in the next drop.  This problem got pointed out to me through other channels recently.  I ended up adopting the $(LIBS) approach.

I know I'm not using git the way it's meant to be used --- apologies for that.  I'll get around to learning it as soon as I figure out how to set the time on my VCR.

**Comment by acxz** [comment]
@ericstoneking no problemo lol, just know that people are willing to help and it will definitely help the project move forward if the development is also a more open.

Once again, thanks for authoring this amazing codebase!

**Comment by ericstoneking** [comment]
Thanks for the kind words!  And thanks for your understanding.  I really do appreciate bug reports and feature requests.  I just have too many draws on my attention to let git be one of them.

**Pull request closed without merging**
